blank_issues_enabled: false
contact_links:
  - name: Steam Workshop page
    url: https://steamcommunity.com/sharedfiles/filedetails/?id=3746092811
    about: Official Steam Workshop page for Auto-Forward Smart Speed.
  - name: Page Steam Workshop
    url: https://steamcommunity.com/sharedfiles/filedetails/?id=3746092811
    about: Page Steam Workshop officielle d’Auto-Forward Smart Speed.
